version: 2.1

executors:
  dock-executor:
    machine:
      enabled: true
      image: circleci/classic:201808-01

jobs:
  container_build:
    executor:
      name: dock-executor
    steps:
      - checkout
      - run:
          name: Build container
          when: always
          command: |
            docker image build -t stuffed_${CIRCLE_BUILD_NUM} .
            docker image ls

workflows:
  version: 2
  defaultWorkflow:
    jobs:
      - container_build
